<?php

namespace ROA\ROABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClasificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionRepository extends EntityRepository
{
}
