<?php

namespace ROA\ROABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{

	public function findComentariosPublicados($id){

		$em = $this->getEntityManager();
		$dql = "select c from ROABundle:comentario c JOIN c.status s WITH s.descripcion LIKE 'Publicado' JOIN c.oa o WITH o.id = '".$id."' ORDER BY c.fecha_publicacion DESC";
		$query = $em->createQuery($dql);
		$comentarios = $query->getResult();
		return $comentarios;
	}

	public function findComentariosNoPublicados(){

		$em = $this->getEntityManager();
		$dql = "select c from ROABundle:comentario c JOIN c.status s WITH s.descripcion LIKE 'No Publicado'";
		$query = $em->createQuery($dql);
		$comentarios = $query->getResult();
		return $comentarios;
	}

	

}
