<?php

namespace ROA\ROABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VocabloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabloRepository extends EntityRepository
{
}
