<?php

namespace ROA\ROABundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IdentificadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificadorRepository extends EntityRepository
{
}
