<?php
namespace ROA\ROABundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UsuarioRepository extends EntityRepository{

	public function findAlfabeticamente(){

		$em = $this->getEntityManager();
		$dql = "select u from ROABundle:Usuario u ORDER BY u.nombre";
		$query = $em->createQuery($dql);
		$usuarios = $query->getResult();
		return $usuarios;

		/*return $this->getEntityManager()->createQuery('SELECT p FROM ROABundle:Usuario')->getResult();*/
	}

	public function findPorRole($role){

		$em = $this->getEntityManager();
		$dql = "select u from ROABundle:Usuario u JOIN u.roles r WITH r.nombre LIKE '".$role."'";
		$query = $em->createQuery($dql);
		$usuarios = $query->getResult();
		return $usuarios;
	}

	public function findPorRole2($role){

		$em = $this->getEntityManager();
		$dql = "select u from ROABundle:Usuario u JOIN u.roles r WITH r.descripcion LIKE '".$role."'";
		$query = $em->createQuery($dql);
		$usuarios = $query->getResult();
		return $usuarios;
	}

}